### ISSUE TITLE
call stack size exceeded

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/arb-bot#66]
```
@opentelemetry/api: Registered a global for diag v1.8.0.
@opentelemetry/api: Registered a global for trace v1.8.0.
@opentelemetry/api: Registered a global for propagation v1.8.0.
{"stack":"RangeError: Maximum call stack size exceeded\n    at Number.toString (<anonymous>)\n    at objStringify (/src/utils.js:1304:43)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
```

**Comment by thedavidmeister** [comment]
```
Starting next round in 0 seconds... 

{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
Starting next round in 0 seconds... 

{"stack":"RangeError: Maximum call stack size exceeded\n    at Function.getOwnPropertyNames (<anonymous>)\n    at objStringify (/src/utils.js:1298:29)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)\n    at objStringify (/src/utils.js:1306:32)","message":"Maximum call stack size exceeded","name":"RangeError"}
Starting next round in 0 seconds...
```
